// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using WatchKit;

namespace WatchOS_Xamarin_Example.On_WatchExtension
{
	public partial class WatchImagenViewController : WKInterfaceController
    {
        public WatchImagenViewController (IntPtr handle) : base (handle)
		{
		}

        public override void Awake(NSObject context)
        {
            base.Awake(context);
            this.SetTitle("Imagenes");
        }
	}
}
