// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using WatchKit;

namespace WatchOS_Xamarin_Example.On_WatchExtension
{
	public partial class WatchModalController : WKInterfaceController
	{
		public WatchModalController (IntPtr handle) : base (handle)
		{
		}


        public override void Awake(NSObject context)
        {
            base.Awake(context);
        }
        partial void backTouch()
        {
            this.DismissController();
        }
	}
}
