// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;
using Foundation;
using WatchKit;


public enum Options
{
    BackToHome,
    Images,
    Switch,
    Map,
    ToIphone
}
namespace WatchOS_Xamarin_Example.On_WatchExtension
{
    public partial class WatchNavigationController : WKInterfaceController
    {

        List<string> Lst_Options;

        public WatchNavigationController(IntPtr handle) : base(handle)
        {
            Lst_Options = Enum.GetNames(typeof(Options)).ToList();
        }

        public override void Awake(NSObject context)
        {
            base.Awake(context);
            SetUpTable();
        }

        private void SetUpTable()
        {
            tableOptions.SetNumberOfRows(Lst_Options.Count,"OptionRow");
            for (int i = 0; i < Lst_Options.Count;i++)
            {
                OptionRow row = (OptionRow)tableOptions.GetRowController(i);
                row.setTitle(Lst_Options[i]);
            }
        }
        public override void DidSelectRow(WKInterfaceTable table, nint rowIndex)
        {
            var option = Lst_Options[(int)rowIndex];
            if (option == "BackToHome")
            {
                this.PopController();
            }
            else if(option == "Images")
            {
                this.PushController("WatchImagenViewController","");
            }
            else if (option=="Switch")
            {
                this.PushController("SwitchInterfaceController","");
            }
            else if (option=="Map")
            {
                this.PushController("MapInterfaceController","");
            }
            else if (option=="ToIphone")
            {
                this.PushController("ToIphoneController", "");
            }
        }
    }
}
